language: node_js
node_js:
  - '4.2.3'

script:
  - sudo apt-get update && sudo apt-get install --only-upgrade google-chrome-stable
  - npm run update-webdriver
  - npm run start-webdriver
  - npm run status-webdriver
  - npm test
