language: node_js
node_js:
  - '4.2.3'

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - npm run update-webdriver
  - npm run start-webdriver
  - npm run status-webdriver
  - 'node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager start 2>&1 &'
  - npm test
