language: node_js
node_js:
  - '4.2.3'

sudo: required

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
  - npm run update-webdriver
  - npm run start-webdriver
  - npm run status-webdriver
  - npm test
