language: node_js
node_js:
  - '4.2.3'

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm run update-webdriver
  - npm run start-webdriver
  - npm run status-webdriver
  - sleep 3

script:
  - npm test
