language: node_js
node_js:
  - '4.2.3'

jdk:
  - oraclejdk8

script:
  - jdk_switcher use oraclejdk8
  - java -version
  - npm run update-webdriver
  - npm run start-webdriver
  - npm run status-webdriver
  - npm test
