language: node_js
node_js:
  - '4.2.3'

# sudo: required
# dist: trusty
# addons:
#   firefox: "44.0"
before_script:
  - npm run update-webdriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run status-webdriver
  - npm test
