language: node_js
node_js:
  - "0.12"
  - "4.0"
  - "4.3"
  - "4"
  - "5.0"
  - "5"
  - "6"
  - "stable"

sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm run update-webdriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run status-webdriver
  - npm test
