language: node_js
node_js:
  - '4.2.3'

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - java -version

script:
  - npm run update-webdriver
  - npm run start-webdriver
  - npm run status-webdriver
  - npm test
