language: node_js
node_js:
  - '4.2.3'

addons:
  firefox: "39.0"

before_script:
  - npm run update-webdriver
  - "export DISPLAY=:99.0"

script:
  # - npm run start-webdriver
  - npm run status-webdriver
  - npm test
