environment:
    matrix:
        - NPM_VERSION: "2"
        - NPM_VERSION: "3"
        # node.js
        - NODE_VERSION: "0.12"
        - NODE_VERSION: "4.0"
        - NODE_VERSION: "4.3"
        - NODE_VERSION: "4"
        - NODE_VERSION: "5.0"
        - NODE_VERSION: "5"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:NODE_VERSION
  - node --version
  - npm --version
  - npm install

build: off

test_script:
  - npm run update-webdriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm test
